{ pkgs, ... }:
let
  arkenfox_default = {
    "app.normandy.api_url" = "";
    "app.normandy.enabled" = false;
    "app.shield.optoutstudies.enabled" = false;
    "breakpad.reportURL" = "";
    "browser.aboutConfig.showWarning" = false;
    "browser.cache.disk.enable" = false;
    "browser.contentanalysis.default_allow" = false;
    "browser.contentblocking.category" = "strict";
    "browser.crashReports.unsubmittedCheck.autoSubmit2" = false;
    "browser.discovery.enabled" = false;
    "browser.display.use_system_colors" = false;
    "browser.download.always_ask_before_handling_new_types" = true;
    "browser.download.alwaysOpenPanel" = false;
    "browser.download.manager.addToRecentDocs" = false;
    "browser.download.start_downloads_in_tmp_dir" = true;
    "browser.download.useDownloadDir" = false;
    "browser.formfill.enable" = false;
    "browser.helperApps.deleteTempFileOnExit" = true;
    "browser.link.open_newwindow" = 3;
    "browser.link.open_newwindow.restriction" = 0;
    "browser.messaging-system.whatsNewPanel.enabled" = false;
    "browser.newtabpage.activity-stream.asrouter.userprefs.cfr.addons" = false;
    "browser.newtabpage.activity-stream.asrouter.userprefs.cfr.features" = false;
    "browser.newtabpage.activity-stream.default.sites" = "";
    "browser.newtabpage.activity-stream.feeds.telemetry" = false;
    "browser.newtabpage.activity-stream.showSponsored" = false;
    "browser.newtabpage.activity-stream.showSponsoredTopSites" = false;
    "browser.newtabpage.activity-stream.telemetry" = false;
    "browser.newtabpage.enabled" = false;
    "browser.ping-centre.telemetry" = false;
    "browser.places.speculativeConnect.enabled" = false;
    "browser.privatebrowsing.forceMediaMemoryCache" = true;
    "browser.safebrowsing.downloads.remote.enabled" = false;
    "browser.search.separatePrivateDefault" = true;
    "browser.search.separatePrivateDefault.ui.enabled" = true;
    "browser.search.suggest.enabled" = false;
    "browser.sessionstore.privacy_level" = 2;
    "browser.shell.shortcutFavicons" = false;
    "browser.shopping.experience2023.enabled" = false;
    "browser.startup.homepage" = "about:blank";
    "browser.startup.homepage_override.mstone" = "ignore";
    "browser.startup.page" = 0;
    "browser.tabs.crashReporting.sendReport" = false;
    "browser.tabs.searchclipboardfor.middleclick" = false;
    "browser.uitour.enabled" = false;
    "browser.urlbar.addons.featureGate" = false;
    "browser.urlbar.mdn.featureGate" = false;
    "browser.urlbar.pocket.featureGate" = false;
    "browser.urlbar.showSearchTerms.enabled" = false;
    "browser.urlbar.speculativeConnect.enabled" = false;
    "browser.urlbar.suggest.searches" = false;
    "browser.urlbar.trending.featureGate" = false;
    "browser.urlbar.weather.featureGate" = false;
    "browser.urlbar.yelp.featureGate" = false;
    "browser.xul.error_pages.expert_bad_cert" = true;
    "captivedetect.canonicalURL" = "";
    "datareporting.healthreport.uploadEnabled" = false;
    "datareporting.policy.dataSubmissionEnabled" = false;
    "devtools.debugger.remote-enabled" = false;
    "dom.disable_window_move_resize" = true;
    "dom.security.https_only_mode_send_http_background_request" = false;
    "dom.security.https_only_mode" = true;
    "extensions.blocklist.enabled" = true;
    "extensions.enabledScopes" = 5;
    "extensions.getAddons.showPane" = false;
    "extensions.htmlaboutaddons.recommendations.enabled" = false;
    "extensions.postDownloadThirdPartyPrompt" = false;
    "extensions.quarantinedDomains.enabled" = true;
    "extensions.webcompat.enable_shims" = true;
    "extensions.webcompat-reporter.enabled" = false;
    "geo.provider.ms-windows-location" = false;
    "geo.provider.network.url" = "";
    "geo.provider.use_corelocation" = false;
    "geo.provider.use_geoclue" = false;
    "geo.provider.use_gpsd" = false;
    "media.memory_cache_max_size" = 65536;
    "media.peerconnection.ice.default_address_only" = true;
    "media.peerconnection.ice.proxy_only_if_behind_proxy" = true;
    "network.auth.subresource-http-auth-allow" = 1;
    "network.captive-portal-service.enabled" = false;
    "network.connectivity-service.enabled" = false;
    "network.dns.disablePrefetch" = true;
    "network.dns.skipTRR-when-parental-control-enabled" = false;
    "network.file.disable_unc_paths" = true;
    "network.gio.supported-protocols" = "";
    "network.http.referer.spoofSource" = false;
    "network.http.referer.XOriginTrimmingPolicy" = 2;
    "network.http.speculative-parallel-limit" = 0;
    "network.IDN_show_punycode" = true;
    "network.predictor.enabled" = false;
    "network.predictor.enable-prefetch" = false;
    "network.prefetch-next" = false;
    "network.proxy.socks_remote_dns" = true;
    "pdfjs.disabled" = false;
    "pdfjs.enableScripting" = false;
    "permissions.manager.defaultsUrl" = "";
    "privacy.clearHistory.cache" = true;
    "privacy.clearHistory.cookiesAndStorage" = false;
    "privacy.clearHistory.historyFormDataAndDownloads" = true;
    "privacy.clearOnShutdown.cache" = true;
    "privacy.clearOnShutdown.cookies" = true;
    "privacy.clearOnShutdown.downloads" = true;
    "privacy.clearOnShutdown.formdata" = true;
    "privacy.clearOnShutdown.history" = true;
    "privacy.clearOnShutdown.offlineApps" = true;
    "privacy.clearOnShutdown.sessions" = true;
    "privacy.clearOnShutdown_v2.cache" = true;
    "privacy.clearOnShutdown_v2.cookiesAndStorage" = true;
    "privacy.clearOnShutdown_v2.historyFormDataAndDownloads" = true;
    "privacy.clearSiteData.cache" = true;
    "privacy.clearSiteData.cookiesAndStorage" = false;
    "privacy.clearSiteData.historyFormDataAndDownloads" = true;
    "privacy.cpd.cache" = true;
    "privacy.cpd.cookies" = false;
    "privacy.cpd.formdata" = true;
    "privacy.cpd.history" = true;
    "privacy.cpd.offlineApps" = false;
    "privacy.cpd.sessions" = true;
    "privacy.firstparty.isolate" = false;
    "privacy.resistFingerprinting.block_mozAddonManager" = true;
    "privacy.resistFingerprinting.letterboxing" = true;
    "privacy.resistFingerprinting" = true;
    "privacy.sanitize.sanitizeOnShutdown" = true;
    "privacy.sanitize.timeSpan" = 0;
    "privacy.spoof_english" = 1;
    "privacy.userContext.enabled" = true;
    "privacy.userContext.ui.enabled" = true;
    "privacy.window.maxInnerHeight" = 900;
    "privacy.window.maxInnerWidth" = 1600;
    "security.cert_pinning.enforcement_level" = 2;
    "security.dialog_enable_delay" = 1000;
    "security.family_safety.mode" = 0;
    "security.OCSP.enabled" = 1;
    "security.OCSP.require" = true;
    "security.pki.crlite_mode" = 2;
    "security.remote_settings.crlite_filters.enabled" = true;
    "security.ssl.require_safe_negotiation" = true;
    "security.ssl.treat_unsafe_negotiation_as_broken" = true;
    "security.tls.enable_0rtt_data" = false;
    "security.tls.version.enable-deprecated" = false;
    "signon.autofillForms" = false;
    "signon.formlessCapture.enabled" = false;
    "toolkit.coverage.endpoint.base" = "";
    "toolkit.coverage.opt-out" = true;
    "toolkit.telemetry.archive.enabled" = false;
    "toolkit.telemetry.bhrPing.enabled" = false;
    "toolkit.telemetry.coverage.opt-out" = true;
    "toolkit.telemetry.enabled" = false;
    "toolkit.telemetry.firstShutdownPing.enabled" = false;
    "toolkit.telemetry.newProfilePing.enabled" = false;
    "toolkit.telemetry.server" = "data:,";
    "toolkit.telemetry.shutdownPingSender.enabled" = false;
    "toolkit.telemetry.unified" = false;
    "toolkit.telemetry.updatePing.enabled" = false;
    "toolkit.winRegisterApplicationRestart" = false;
    "webchannel.allowObject.urlWhitelist" = "";
    "webgl.disabled" = true;
    "widget.non-native-theme.enabled" = true;
  };
  # see 'https://wiki.debian.org/Firefox#Disabling_automatic_connections'
  disable_telemetry = {
    "app.update.enabled" = false;
    "app.update.auto" = false;
    "app.update.url.details" = "";
    "app.update.url.manual" = "";
    "browser.search.update" = false;
    "extensions.update.enabled" = false;
    "toolkit.telemetry.archive.enabled" = false;
    "toolkit.telemetry.enabled" = false;
    "toolkit.telemetry.server" = "";
    "toolkit.telemetry.unified" = false;
  };
  custom_settings = {
    "browser.casting.enabled" = false;
    "browser.download.folderList" = 2;
    "browser.download.forbid_open_with" = true;
    "browser.translations.enable" = false;
    "browser.uitour.url" = "";
    "browser.urlbar.suggest.history" = false;
    "browser.urlbar.suggest.openpage" = false;
    "browser.urlbar.suggest.topsites" = false;
    "dom.popup_allowed_events" = "click dblclick mousedown pointerdown";
    "extensions.autoDisableScopes" = 15;
    "extensions.formautofill.addresses.enabled" = false;
    "extensions.formautofill.creditCards.enabled" = false;
    "keyword.enabled" = false;
    "layout.css.visited_links_enabled" = false;
    "media.gmp-gmpopenh264.enabled" = false;
    "media.gmp-provider.enabled" = false;
    "media.peerconnection.ice.no_host" = true;
    "network.proxy.allow_bypass" = false;
    "network.trr.custom_uri" = "https://dns.quad9.net/dns-query";
    "network.trr.mode" = 3;
    "network.trr.uri" = "https://dns.quad9.net/dns-query";
    "permissions.default.shortcuts" = 2;
    "places.history.enabled" = false;
    "privacy.fingerprintingProtection.remoteOverrides.enabled" = false;
    "privacy.resistFingerprinting.randomization.daily_reset.enabled" = true;
    "privacy.resistFingerprinting.randomization.daily_reset.private.enabled" = true;
    "privacy.trackingprotection.enabled" = true;
    "security.mixed_content.block_display_content" = true;
    "signon.rememberSignons" = false;

    # dark theme
    "ui.systemUsesDarkTheme" = 1;
    "layout.css.prefers-color-scheme.content-override" = 0;
    "extensions.activeThemeID" = "default-theme@mozilla.org";

    # https://www.theregister.com/2024/06/18/mozilla_buys_anonym_betting_privacy/
    "dom.private-attribution.submission.enabled" = "false";
  };

  #TODO: incorporate https://github.com/pyllyukko/user.js
in
{
  programs.firefox = {
    enable = true;
    preferences = arkenfox_default // disable_telemetry // custom_settings;

    policies.ExtensionSettings = {
      # blocks all addons except the ones specified below
      "*".installation_mode = "blocked";

      # uMatrix:
      "uMatrix@raymondhill.net" = {
        install_url = "https://addons.mozilla.org/firefox/downloads/latest/uMatrix/latest.xpi";
        installation_mode = "force_installed";
      };

      # Privacy Badger:
      "jid1-MnnxcxisBPnSXQ@jetpack" = {
        install_url = "https://addons.mozilla.org/firefox/downloads/latest/privacy-badger17/latest.xpi";
        installation_mode = "force_installed";
      };
    };
  };
}
